import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/letsstarted">LetsStarted</Link>
        </li>
        <li>
          <Link to="/welcomeback">WelcomeBack</Link>
        </li>
        <li>
          <Link to="/videokycconsent">VideoKYCConsent</Link>
        </li>
        <li>
          <Link to="/uploadpancard">UploadPanCard</Link>
        </li>
        <li>
          <Link to="/uploadaadharcard">UploadAadharCard</Link>
        </li>
        <li>
          <Link to="/getonvideocall">GetonVideocall</Link>
        </li>
        <li>
          <Link to="/getonvideocallone">GetonVideocallOne</Link>
        </li>
        <li>
          <Link to="/videocalltwo">VideoCallTwo</Link>
        </li>
        <li>
          <Link to="/kycphotoclickone">KYCPhotoClickOne</Link>
        </li>
        <li>
          <Link to="/kycphotoclick">KYCPhotoClick</Link>
        </li>
        <li>
          <Link to="/kycphotoclicktwo">KYCPhotoClickTwo</Link>
        </li>
        <li>
          <Link to="/videokycthree">VideoKYCThree</Link>
        </li>
        <li>
          <Link to="/videokycfive">VideoKYCFive</Link>
        </li>
        <li>
          <Link to="/videocall">VideoCall</Link>
        </li>
        <li>
          <Link to="/videocallone">VideoCallOne</Link>
        </li>
        <li>
          <Link to="/pancardcapture">PanCardCapture</Link>
        </li>
        <li>
          <Link to="/pancardverification">PanCardVerification</Link>
        </li>
        <li>
          <Link to="/photocapture">PhotoCapture</Link>
        </li>
        <li>
          <Link to="/faceverification">FaceVerification</Link>
        </li>
        <li>
          <Link to="/signaturecapture">SignatureCapture</Link>
        </li>
        <li>
          <Link to="/signatureverification">SignatureVerification</Link>
        </li>
        <li>
          <Link to="/videokyctwo">VideoKYCTwo</Link>
        </li>
        <li>
          <Link to="/videokyc">VideoKYC</Link>
        </li>
        <li>
          <Link to="/videokycfour">VideoKYCFour</Link>
        </li>
        <li>
          <Link to="/videokycone">VideoKYCOne</Link>
        </li>
        <li>
          <Link to="/dashboardone">DashboardOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
